<?php
/**
 * SearchRefinementResult
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  AmazonBusinessApi
 */

/**
 * Amazon Business API for Products
 *
 * An API for getting data about products available to Amazon Business customers. This includes information such as the product title, the merchant selling the product, and the current price.
 *
 * The version of the OpenAPI document: 2020-08-26
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AmazonBusinessApi\Model\ProductSearchV20200826;
use AmazonBusinessApi\Model\BaseModel;
use \AmazonBusinessApi\Model\ModelInterface;
use \AmazonBusinessApi\ObjectSerializer;
use \ArrayAccess;

/**
 * SearchRefinementResult Class Doc Comment
 *
 * @category Class
 * @description Search refinements is used to share the refinements available for search result which can be used in subsequent request to narrow down the results , for example search category is a type of search refinement, if search category refinement is used in request , search results will be limited to given search category.
 * @package  AmazonBusinessApi
 * @group 
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class SearchRefinementResult extends BaseModel implements ModelInterface, ArrayAccess, \JsonSerializable, \IteratorAggregate
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SearchRefinementResult';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'selection_type' => 'string',
        'display_value' => 'string',
        'refinement_values' => '\AmazonBusinessApi\Model\ProductSearchV20200826\RefinementValue[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'selection_type' => null,
        'display_value' => null,
        'refinement_values' => null
    ];



    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'selection_type' => 'selectionType',
        'display_value' => 'displayValue',
        'refinement_values' => 'refinementValues'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
                'selection_type' => 'setSelectionType',
        'display_value' => 'setDisplayValue',
        'refinement_values' => 'setRefinementValues'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'selection_type' => 'getSelectionType',
        'display_value' => 'getDisplayValue',
        'refinement_values' => 'getRefinementValues'
    ];


    
    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['selection_type'] = $data['selection_type'] ?? null;
        $this->container['display_value'] = $data['display_value'] ?? null;
        $this->container['refinement_values'] = $data['refinement_values'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];
        if ($this->container['selection_type'] === null) {
            $invalidProperties[] = "'selection_type' can't be null";
        }
        if ($this->container['display_value'] === null) {
            $invalidProperties[] = "'display_value' can't be null";
        }
        if ($this->container['refinement_values'] === null) {
            $invalidProperties[] = "'refinement_values' can't be null";
        }
        return $invalidProperties;
    }


    /**
     * Gets selection_type
     *
     * @return string
     */
    public function getSelectionType()
    {
        return $this->container['selection_type'];
    }

    /**
     * Sets selection_type
     *
     * @param string $selection_type SelectionType is used to identify selection allowed for a given refinement, for example MultiSelect allows to search with multiple values of a refinement and InsteadSelect allows to search with only single refinement value
     *
     * @return self
     */
    public function setSelectionType($selection_type)
    {
        $this->container['selection_type'] = $selection_type;

        return $this;
    }
    /**
     * Gets display_value
     *
     * @return string
     */
    public function getDisplayValue()
    {
        return $this->container['display_value'];
    }

    /**
     * Sets display_value
     *
     * @param string $display_value Human friendly name of a given refinement type
     *
     * @return self
     */
    public function setDisplayValue($display_value)
    {
        $this->container['display_value'] = $display_value;

        return $this;
    }
    /**
     * Gets refinement_values
     *
     * @return \AmazonBusinessApi\Model\ProductSearchV20200826\RefinementValue[]
     */
    public function getRefinementValues()
    {
        return $this->container['refinement_values'];
    }

    /**
     * Sets refinement_values
     *
     * @param \AmazonBusinessApi\Model\ProductSearchV20200826\RefinementValue[] $refinement_values RefinementValues holds items for a given refinement, for example if Brand is a refinement then refinementValues will have different brands available for a given product
     *
     * @return self
     */
    public function setRefinementValues($refinement_values)
    {
        $this->container['refinement_values'] = $refinement_values;

        return $this;
    }
}


