<?php
/**
 * CreateBusinessUserAccountRequest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  AmazonBusinessApi
 */

/**
 * Amazon Business API for Managing Accounts.
 *
 * An API for managing Amazon Business accounts.
 *
 * The version of the OpenAPI document: 2021-08-30
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace AmazonBusinessApi\Model\UserManagementV20210830;
use AmazonBusinessApi\Model\BaseModel;
use AmazonBusinessApi\Model\ModelInterface;
use AmazonBusinessApi\ObjectSerializer;
use ArrayAccess;

/**
 * CreateBusinessUserAccountRequest Class Doc Comment
 *
 * @category Class
 * @description A request to create a business user account.
 * @package  AmazonBusinessApi
 * @group 
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null  
 */
class CreateBusinessUserAccountRequest extends BaseModel implements ModelInterface, ArrayAccess, \JsonSerializable, \IteratorAggregate
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateBusinessUserAccountRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'account_holder' => '\AmazonBusinessApi\Model\UserManagementV20210830\AccountHolder',
        'group_id' => '\AmazonBusinessApi\Model\UserManagementV20210830\BusinessGroupIdentifier',
        'role' => '\AmazonBusinessApi\Model\UserManagementV20210830\BusinessRole',
        'region' => '\AmazonBusinessApi\Model\UserManagementV20210830\Region',
        'notification_types_to_suppress' => '\AmazonBusinessApi\Model\UserManagementV20210830\NotificationType[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'account_holder' => null,
        'group_id' => null,
        'role' => null,
        'region' => null,
        'notification_types_to_suppress' => null
    ];



    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'account_holder' => 'accountHolder',
        'group_id' => 'groupId',
        'role' => 'role',
        'region' => 'region',
        'notification_types_to_suppress' => 'notificationTypesToSuppress'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
                'account_holder' => 'setAccountHolder',
        'group_id' => 'setGroupId',
        'role' => 'setRole',
        'region' => 'setRegion',
        'notification_types_to_suppress' => 'setNotificationTypesToSuppress'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'account_holder' => 'getAccountHolder',
        'group_id' => 'getGroupId',
        'role' => 'getRole',
        'region' => 'getRegion',
        'notification_types_to_suppress' => 'getNotificationTypesToSuppress'
    ];


    
    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['account_holder'] = $data['account_holder'] ?? null;
        $this->container['group_id'] = $data['group_id'] ?? null;
        $this->container['role'] = $data['role'] ?? null;
        $this->container['region'] = $data['region'] ?? null;
        $this->container['notification_types_to_suppress'] = $data['notification_types_to_suppress'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];
        if ($this->container['account_holder'] === null) {
            $invalidProperties[] = "'account_holder' can't be null";
        }
        if ($this->container['group_id'] === null) {
            $invalidProperties[] = "'group_id' can't be null";
        }
        if ($this->container['role'] === null) {
            $invalidProperties[] = "'role' can't be null";
        }
        if ($this->container['region'] === null) {
            $invalidProperties[] = "'region' can't be null";
        }
        return $invalidProperties;
    }


    /**
     * Gets account_holder
     *
     * @return \AmazonBusinessApi\Model\UserManagementV20210830\AccountHolder
     */
    public function getAccountHolder()
    {
        return $this->container['account_holder'];
    }

    /**
     * Sets account_holder
     *
     * @param \AmazonBusinessApi\Model\UserManagementV20210830\AccountHolder $account_holder account_holder
     *
     * @return self
     */
    public function setAccountHolder($account_holder)
    {
        $this->container['account_holder'] = $account_holder;

        return $this;
    }
    /**
     * Gets group_id
     *
     * @return \AmazonBusinessApi\Model\UserManagementV20210830\BusinessGroupIdentifier
     */
    public function getGroupId()
    {
        return $this->container['group_id'];
    }

    /**
     * Sets group_id
     *
     * @param \AmazonBusinessApi\Model\UserManagementV20210830\BusinessGroupIdentifier $group_id group_id
     *
     * @return self
     */
    public function setGroupId($group_id)
    {
        $this->container['group_id'] = $group_id;

        return $this;
    }
    /**
     * Gets role
     *
     * @return \AmazonBusinessApi\Model\UserManagementV20210830\BusinessRole
     */
    public function getRole()
    {
        return $this->container['role'];
    }

    /**
     * Sets role
     *
     * @param \AmazonBusinessApi\Model\UserManagementV20210830\BusinessRole $role role
     *
     * @return self
     */
    public function setRole($role)
    {
        $this->container['role'] = $role;

        return $this;
    }
    /**
     * Gets region
     *
     * @return \AmazonBusinessApi\Model\UserManagementV20210830\Region
     */
    public function getRegion()
    {
        return $this->container['region'];
    }

    /**
     * Sets region
     *
     * @param \AmazonBusinessApi\Model\UserManagementV20210830\Region $region region
     *
     * @return self
     */
    public function setRegion($region)
    {
        $this->container['region'] = $region;

        return $this;
    }
    /**
     * Gets notification_types_to_suppress
     *
     * @return \AmazonBusinessApi\Model\UserManagementV20210830\NotificationType[]|null
     */
    public function getNotificationTypesToSuppress()
    {
        return $this->container['notification_types_to_suppress'];
    }

    /**
     * Sets notification_types_to_suppress
     *
     * @param \AmazonBusinessApi\Model\UserManagementV20210830\NotificationType[]|null $notification_types_to_suppress A list of enums that specifies the types of notification to suppress.
     *
     * @return self
     */
    public function setNotificationTypesToSuppress($notification_types_to_suppress)
    {
        $this->container['notification_types_to_suppress'] = $notification_types_to_suppress;

        return $this;
    }
}


